---
sudo: required
language: ruby
services:
  - docker
before_install:
  - docker build -t franklinkim/ansible-trusty .
script:
  - docker run -d franklinkim/ansible-trusty /bin/sh -c "while true; do ping 8.8.8.8; sleep 1; done"
  - docker ps -a
after_script:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push franklinkim/ansible-trusty
